/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViniRouteImport } from './routes/vini'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DrinkRouteImport } from './routes/drink'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CaffetteriaRouteImport } from './routes/caffetteria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ViniRoute = ViniRouteImport.update({
  id: '/vini',
  path: '/vini',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkRoute = DrinkRouteImport.update({
  id: '/drink',
  path: '/drink',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CaffetteriaRoute = CaffetteriaRouteImport.update({
  id: '/caffetteria',
  path: '/caffetteria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caffetteria': typeof CaffetteriaRoute
  '/contatti': typeof ContattiRoute
  '/drink': typeof DrinkRoute
  '/menu': typeof MenuRoute
  '/vini': typeof ViniRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caffetteria': typeof CaffetteriaRoute
  '/contatti': typeof ContattiRoute
  '/drink': typeof DrinkRoute
  '/menu': typeof MenuRoute
  '/vini': typeof ViniRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caffetteria': typeof CaffetteriaRoute
  '/contatti': typeof ContattiRoute
  '/drink': typeof DrinkRoute
  '/menu': typeof MenuRoute
  '/vini': typeof ViniRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caffetteria'
    | '/contatti'
    | '/drink'
    | '/menu'
    | '/vini'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caffetteria'
    | '/contatti'
    | '/drink'
    | '/menu'
    | '/vini'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/caffetteria'
    | '/contatti'
    | '/drink'
    | '/menu'
    | '/vini'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaffetteriaRoute: typeof CaffetteriaRoute
  ContattiRoute: typeof ContattiRoute
  DrinkRoute: typeof DrinkRoute
  MenuRoute: typeof MenuRoute
  ViniRoute: typeof ViniRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vini': {
      id: '/vini'
      path: '/vini'
      fullPath: '/vini'
      preLoaderRoute: typeof ViniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink': {
      id: '/drink'
      path: '/drink'
      fullPath: '/drink'
      preLoaderRoute: typeof DrinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caffetteria': {
      id: '/caffetteria'
      path: '/caffetteria'
      fullPath: '/caffetteria'
      preLoaderRoute: typeof CaffetteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaffetteriaRoute: CaffetteriaRoute,
  ContattiRoute: ContattiRoute,
  DrinkRoute: DrinkRoute,
  MenuRoute: MenuRoute,
  ViniRoute: ViniRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
